### PR TITLE
allow optional +

### LINKED ISSUE #36: allow `+` in project configs to be optional
we should make sure the we don't absolutely require project level configs to include the `+`

### PR DESCRIPTION
**Pull request by dave-connors-3**
For any config, use `patternProperties` allow for an optional `+` at the start of the key name

closes #36

### CODE REVIEW

**Comment by joellabes** [comment]
@dave-connors-3 I _think_ I tried doing this last year, and discovered that pattern-based columns prevent autocomplete from working in most systems, because the IDE doesn't know what it can sensibly offer up. 

So I might be a buzzkill on this and suggest that we have to duplicate everything with and without pluses 😬 (or insist on people using the pluses? they are _more_ correct, although since there's no equivalent to `sqlfluff fix` for a JSON Schema the migration would be painful for anyone trying to do that)

**Comment by dave-connors-3** [comment]
i am in accordance with your feedback! autocomplete and highlighting on both versions feels like a better overall experience for people

**Comment by dave-connors-3** [comment]
@joellabes ready for rereview!

**Comment by joellabes** [comment]
@dave-connors-3 here's some other thoughts, as I look at that big wall of copy-paste and grimace at the thought of keeping them in sync:
- could we script this in a GHA so that we only add the +ed version and it adds a +less variant?
- should we do everything as defs (this feels like the equivalent of having a dbt model whose only content is a one-line macro, a pattern that I dislike but is my least disliked pattern overall)
- both of the above?

**Comment by dave-connors-3** [comment]
@joellabes made the update we discussed -- for each config, there's now a reference in `defs` for the definition of that config, and then a plus and non-plus version that references that definition. Anything that _already_ referenced a definition (like `docs_config` for example, was left alone, and the duplicated non-plus entry should point to the same definition.

**Comment by joellabes** [comment]
@dave-connors-3 this looks great! I have just added a CI test (you can see the results [here](https://github.com/dbt-labs/dbt-jsonschema/actions/runs/4412108530/jobs/7731254071), [here](https://github.com/dbt-labs/dbt-jsonschema/actions/runs/4412114410/jobs/7731266998) and [here](https://github.com/dbt-labs/dbt-jsonschema/actions/runs/4412120968/jobs/7731279883) if you'd like to see what the output is) to validate that every key exists with/without a plus, and that their contents are identical. 

Strictly speaking, it is inefficient to validate that the objects are identical in both directions, but I have to check the keys have counterparts in both directions and decided that it didn't matter enough to optimise. 

Therefore I've approved this but not merged it - you can make sure you're happy with _my_ changes, and if you are then merge away!

**Review by joellabes — APPROVED** [review]

**Comment by dave-connors-3** [comment]
thank you @joellabes

**Pull request merged**
